### ISSUE TITLE
Add a "copy clean code to clipboard" button

### ISSUE THREAD

**Issue by Wildebrew** [lloydi/markup-de-crapulator#15]

**Comment by Wildebrew** [comment]
The 80-character braille optimized feature is just absolutely brilliant for screen reader users!
There are two other things that would take this tool from great to near-perfect for a [blind accessibility tester](http://www.bats.fyi), this is one of the two.
It takes some screen reader gymnastics to copy the clean code from the webpage into notepad or another text editor for analysis.
To make this easier, the code could either be displayed in a `<textarea>` element (in which case you can focus on the area and use ctrl-a + ctrl-c to copy, then paste somewhere else) or add a "copy to clipboard" button that, when clicked, copies the clean code with the desired formatting to the user's clipboard.
Again, this is not a bug or a critical problem but an enhancement request.
There are ways to copy the code from the page as is, it just takes longer.

**Comment by lloydi** [comment]
Will look at options for this for you. The reason for not using a textarea is because the markup has syntax coloring which is very handy for pasting into Word etc. So I will provide the option to output to rich text or plain text.

**Comment by lloydi** [comment]
Now fixed - check out the new preferences section, @Wildebrew
