### ISSUE TITLE
Add custom list of attributes to abbreviate (or allow any attribute to be abbreviated/stripped)

### ISSUE THREAD

**Issue by matatk** [lloydi/markup-de-crapulator#19]
...in order to match the strip option.

As an alternative to allowing the user to type in custom attributes, you could just allow them to pick _any_ of the attributes found for either abbreviation or removal. (That's what http://matatk.agrip.org.uk/tinker/html-attribute-filter/ does and I think it gives flexibility without you having to anticipate any of the attributes or use-cases for the tool—and if you feel it complicates the UI too much, you could always hide it by default.)

**Comment by lloydi** [comment]
Taking a look at this too. Will probably leave visible options largely as they are but implement the complete list as an extra option shown in a modal or similar.

**Comment by lloydi** [comment]
Now added as a feature.
