### ISSUE TITLE
Issue link obstructed by poop

### ISSUE THREAD

**Issue by aardrian** [lloydi/markup-de-crapulator#20]
When I went to click the link at the bottom of the page to file an issue, I came at it from the right and the link could not be clicked until I got to the left side of it. Turns out it was because the `<div class="poop">` is occluding it.

If you look in the dev tools to compare the edge of the `<div>` with where you can click that link, you will see it in action.

![Browser dev tools highlighting the hidden box, the link, and the opacity style that makes the box almost completely transparent.](https://user-images.githubusercontent.com/1376607/124982419-ab198700-e004-11eb-92c8-23106b043b16.jpg)

**Comment by lloydi** [comment]
Oh poop. The De-Crapulator has a poop overspill problem. Thanks for catching this … poop.

**Comment by lloydi** [comment]
De-pooped
