### ISSUE TITLE
Turd-O-Meter not visible when using Windows High Contrast Mode / forced-colors

### ISSUE THREAD

**Issue by carrythebanner** [lloydi/markup-de-crapulator#24]
The Turd-O-Meter, which measures the degree of HTML De-crapification*, is visually separated from the background by a contrasting background color. This works fine under default conditions, but isn't visible in Windows High Contrast Mode / `forced-colors`. Adding a 1px transparent border to the meter element will make it visible in forced-colors mode and won't affect the default presentation.

*Favorite start to a bug report ever, thanks 😂

**Comment by lloydi** [comment]
No shit. I mean, literally. I better get my shit together then :D

**Comment by lloydi** [comment]
Pooped out a fix for this.
