### ISSUE TITLE
Feature request - insert new line between html elements

### ISSUE THREAD

**Issue by Wildebrew** [lloydi/markup-de-crapulator#7]
First off, this is brilliant!
As a blind developer/tester I'm always looking for time savers when reviewing HTML code, this is exactly the kind of thing I need to get to the essence of a problem rather than spending a lot of time with a text editor and braille display clearing up junk code.
One thing I need to be able to do is to put the start of an HTML element on a new line (i.e. insert a newline between &lt; and &gt; characters).
Braille displays are limited to 80 characters and it's often tricky to locate / split HTML elements.
I've written a RegEx expression that works in a text editor but that editor has its accessibility issues so the progress is slow, being able to just take care of it online would be fantabulously greatastic.

**Comment by lloydi** [comment]
I will try to implement this if I can. The only problem is that the formatting aspect of the output (indenting etc) is the one aspect of this tool where I rely on another library and I am not sure how easily I can change it. That said, it may be a case of letting the formatter do it's work and then to provide a final step *after* that which does the the step of adding line breaks before all opening HTML tags. I will see what I can do to accommodate this.

**Comment by lloydi** [comment]
@Wildebrew I have had a go at something for you to try - check this version out here:

https://lloydi.com/a11y-tools/markup-de-crapulator-braille-friendly/index.html

Note that the option to display in a Braille-friendly format is in a checkbox that is after the generated output. It will toggle the output from the indented markup to unintended version set to 80 char width maximum and with new lines for all opening and closing HTML tags. Feedback welcome.

**Comment by Wildebrew** [comment]
Awesome! If it can easily be added it would be huge for blind
developers/testers, but may be of limited value to others.

On 1/4/21, Ian Lloyd <notifications@github.com> wrote:
> @Wildebrew I have had a go at something for you to try - check this version
> out here:
>
> https://lloydi.com/a11y-tools/markup-de-crapulator-braille-friendly/index.html
>
> Note that the option to display in a Braille-friendly format is in a
> checkbox that is after the generated output. It will toggle the output from
> the indented markup to unintended version set to 80 char width maximum and
> with new lines for all opening and closing HTML tags. Feedback welcome.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/lloydi/markup-de-crapulator/issues/7#issuecomment-753926240


-- 
Work hard. Have fun. Make history.

**Comment by lloydi** [comment]
> Awesome! If it can easily be added it would be huge for blind developers/testers, but may be of limited value to others.
> […](#)
> On 1/4/21, Ian Lloyd ***@***.***> wrote: @Wildebrew I have had a go at something for you to try - check this version out here: https://lloydi.com/a11y-tools/markup-de-crapulator-braille-friendly/index.html Note that the option to display in a Braille-friendly format is in a checkbox that is after the generated output. It will toggle the output from the indented markup to unintended version set to 80 char width maximum and with new lines for all opening and closing HTML tags. Feedback welcome. -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#7 (comment)](https://github.com/lloydi/markup-de-crapulator/issues/7#issuecomment-753926240)
> -- Work hard. Have fun. Make history.

I have made a further change. Please check this version:

https://lloydi.com/a11y-tools/markup-de-crapulator-braille-friendly/

If you find the changes work for you, I will add to the main branch and update the tool (you're accessing a test version with the link above)

**Comment by lloydi** [comment]
I didn't hear back from you about whether this did what you want but I implemented it anyway, So there's a Braille-friendly option in there now, @Wildebrew
