### ISSUE TITLE
When elements contain question marks, indentation goes wonky

### ISSUE THREAD

**Issue by matatk** [lloydi/markup-de-crapulator#8]
Try this...

```html
<div>
  <div>How are you?</div>
</div>
```

It comes out as...

```html
<div>
  <div>How are you?</div>
    </div>
```

**Comment by lloydi** [comment]
I'm not sure how much I can do about that as I am someone else's script to do the indenting. I have noticed that sometimes it doesn't quite get it right. When I get a moment I will re-visit to see if this is within my control to fix.

**Comment by lloydi** [comment]
Haven't forgotten about this, haven't had a clear moment to properly investigate whether this is something that I can easily change or whether this is a problem with the indent js.

**Comment by lloydi** [comment]
Actualy, I know a quick and dirty (ish) way of handling this without needing to worry about why it is happening. :)

**Comment by lloydi** [comment]
Fixed no @matatk :)
